sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    title:      SIS - PLANTILLA
    title_logo: /bundles/applicationcore/images/escudo.png
    templates:
            # default global templates
            layout:  SonataAdminBundle::layout.html.twig
            ajax:    SonataAdminBundle::ajax_layout.html.twig

            # default actions templates, should extend a global templates
            list:    SonataAdminBundle:CRUD:list.html.twig
            show:    SonataAdminBundle:CRUD:show.html.twig
            edit:    ApplicationCoreBundle:CRUD:edit.html.twig

            dashboard: SonataAdminBundle:Core:dashboard.html.twig

    options:
        confirm_exit: false
        use_stickyforms: false

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
