sonata_doctrine_orm_admin:
    templates:
        types:
            show:
                html:    ApplicationCoreBundle:CRUD:FieldType/show_field_html.html.twig
                money:   ApplicationCoreBundle:CRUD:FieldType/show_field_money.html.twig
                file:    ApplicationCoreBundle:CRUD:FieldType/show_field_file.html.twig
