sonata_core:
    flashmessage:
        warning:
            types:
                - { type: sonata_flash_warning, domain: SonataCoreBundle }
                - { type: session_expired_warning, domain: SonataCoreBundle }
