imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bundles/fos_user.yml }
    - { resource: bundles/ivory_ckeditor.yml }
    - { resource: bundles/sonata_admin.yml }
    - { resource: bundles/sonata_block.yml }
    - { resource: bundles/sonata_cache.yml }
    - { resource: bundles/sonata_core.yml }
    - { resource: bundles/sonata_doctrine_orm_admin.yml }
    - { resource: bundles/sonata_formatter.yml }
    - { resource: bundles/sonata_user.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 0
        gc_probability:  0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    globals:
        max_iddle_time: %session_max_idle_time%

    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'ApplicationCoreBundle:CRUD:FieldType/edit_field_file.html.twig'
            - 'ShtumiUsefulBundle::fields.html.twig'
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
      #  driver: "%database_driver%"
        driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        default_entity_manager: default
        dql:
            string_functions:
                COALESCE:   Application\CoreBundle\Dql\CoalesceDql
                CONCAT_WS:  Application\CoreBundle\Dql\ConcatWsDql
                TO_CHAR:    Application\CoreBundle\Dql\ToCharDql
                UNACCENT:   Application\CoreBundle\Dql\UnaccentString
            numeric_functions:
                TO_NUMBER:  Application\CoreBundle\Dql\ToNumberDql

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    encryption: %mailer_encryption%
    port:       %mailer_port%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:     { type: memory }

# Knp MenuBundle
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

#Servicios
services:
    app.twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: 'twig.extension' }

    request_listener.service:
        class: Application\CoreBundle\EventListener\LoginRequestListener
        arguments: ["@security.authorization_checker", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onLoginRequest }

    jasper.build.reports:
        class: Application\CoreBundle\Service\JasperReportService\JasperReportService
        arguments: [%jasper_username%, %jasper_password%, %jasper_url%]

    mail.service:
        class:        Application\CoreBundle\Service\MailService
        arguments:   [@service_container]

    session_idle.service:
        class: Application\CoreBundle\EventListener\TimeOutListener
        arguments: ["@session", "@security.authorization_checker", "@security.token_storage", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    sonata.admin.orm.filter.type.string:
        class: Application\CoreBundle\Filter\CaseInsensitiveStringFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_string }

    application_core_bundle.file_type_extension:
        class: Application\CoreBundle\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

knp_snappy:
    pdf:
        enabled:    true
        binary:     "%kernel.root_dir%/../vendor/bin/wkhtmltopdf-amd64"
        options:    []

circle_rest_client:
    curl:
      defaults:
        CURLOPT_HTTPHEADER:     [ 'Content-Type: application/json' ]
        CURLOPT_FOLLOWLOCATION: true
