utec_transporte:
    resource: "@UtecTransporteBundle/Controller/"
    type:     annotation
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path:  /admin/login
        permanent: true

_inicio:
    path:  /
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

application_core:
    resource: "@ApplicationCoreBundle/Controller/"
    type:     annotation
    prefix:   /

application_soap_routing:
    resource: '@ApplicationSoapBundle/Resources/config/routing.yml'
    prefix: /

application_api_security:
    resource: "@ApplicationApiSecurityBundle/Controller/"
    type:     annotation
    prefix:   /api

# Sonata AdminBundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Sonata CacheBundle
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

# Sonata UserBundle
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#Shtumi Useful
shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'
